Filtered cellgroup markers: {}
barcodes: {}
cellmeta: {}
clusering_slotnames:
    replacements:
    -   __index__: 0
        find_pattern: (.*)
        replace_pattern: louvain_resolution_\1
filter_cells:
    categories: []
    export_mtx: 'true'
    force_recalc: 'false'
    gene_name: gene_symbols
    input_format: anndata
    output_format: anndata_h5ad
    parameters:
    -   __index__: 0
        max: '1000000000.0'
        min: '400.0'
        name: n_genes
    -   __index__: 1
        max: '1000000000.0'
        min: '0.0'
        name: n_counts
    subsets: []
filter_genes:
    categories: []
    export_mtx: 'true'
    force_recalc: 'false'
    input_format: anndata
    output_format: anndata_h5ad
    parameters:
    -   __index__: 0
        max: '1000000000.0'
        min: '3.0'
        name: n_cells
    subsets:
    -   __index__: 0
        name: index
        subset:
            __class__: ConnectedValue
find_clusters:
    input_format: anndata
    method: louvain
    output_cluster: 'true'
    output_format: anndata_h5ad
    settings:
        __current_case__: 1
        default: 'false'
        directed: 'true'
        key_added: METHOD_resolution_RESOLUTION
        layer: ''
        neighbors_key: neighbors
        random_seed: '1234'
        resolution: '1.0'
        resolution_file:
            __class__: ConnectedValue
        restrict_to: ''
        use_weights: 'false'
find_markers:
    groupby: INPUT_OBJ
    input_format: anndata
    n_genes: '100'
    output_format: anndata_h5ad
    output_markers: 'true'
    settings:
        __current_case__: 1
        default: 'false'
        groups: ''
        key_added: markers_GROUPBY
        max_out_group_fraction: '1.0'
        method: t-test_overestim_var
        min_fold_change: '1.0'
        min_in_group_fraction: '0.0'
        pts: 'false'
        rankby_abs: 'false'
        reference: rest
        tie_correct: 'false'
        use_raw: 'true'
find_variable_genes:
    batch_key: ''
    filter: 'false'
    flavor: seurat
    input_format: anndata
    max_disp: '50.0'
    max_mean: '1000000000.0'
    min_disp: '0.5'
    min_mean: '0.0125'
    n_bin: '20'
    n_top_gene: ''
    output_format: anndata_h5ad
    span: '0.3'
genes: {}
gtf: {}
harmony_batch:
    adjusted_basis: X_pca
    basis: X_pca
    batch_key: BATCH_VARIABLE
    input_format: anndata
    output_format: anndata_h5ad
    settings:
        __current_case__: 0
        default: 'true'
make_project_file:
    copy_adata_to_raw: 'false'
    copy_e:
        __current_case__: 0
        default: 'true'
        embedding_keys:
        -   __index__: 0
            contains: tsne
        -   __index__: 1
            contains: umap
        embedding_sources:
            __class__: ConnectedValue
    copy_o:
        __current_case__: 0
        default: 'true'
        obs_keys:
        -   __index__: 0
            contains: louvain
        obs_sources:
            __class__: ConnectedValue
    copy_u:
        __current_case__: 0
        default: 'true'
        uns_keys:
        -   __index__: 0
            contains: marker
        uns_sources:
            __class__: ConnectedValue
    gene_flags: []
    gene_symbols_field: index
    modifications: []
    output_format: anndata_h5ad
    sanitize_varm: 'false'
    top_genes: '50'
matrix: {}
merge_group_slotnames:
    advanced:
        conflict:
            __current_case__: 3
            duplicate_options: keep_first
    inputs:
    -   __index__: 0
        input:
            __class__: ConnectedValue
    -   __index__: 1
        input:
            __class__: ConnectedValue
merged_embeddings:
    advanced:
        conflict:
            __current_case__: 3
            duplicate_options: keep_first
    inputs:
    -   __index__: 0
        input:
            __class__: ConnectedValue
    -   __index__: 1
        input:
            __class__: ConnectedValue
metadata_group_vars: {}
n_neighbors:
    input_type:
        __current_case__: 0
        input_values: 3, 5, 10, 15, 20, 25, 30, 50, 100
        parameter_values: list_comma_separated_values
    parameter_name: n_neighbors
neighbours:
    input_format: anndata
    output_format: anndata_h5ad
    settings:
        __current_case__: 1
        default: 'false'
        key_added: ''
        knn: 'true'
        method: umap
        metric: euclidean
        n_neighbors: '15'
        n_neighbors_file:
            __class__: RuntimeValue
        n_pcs: '50'
        random_seed: '0'
        use_rep: X_pca
neighbours for umap:
    input_format: anndata
    output_format: anndata_h5ad
    settings:
        __current_case__: 1
        default: 'false'
        key_added: neighbors_n_neighbors_N_NEIGHBORS
        knn: 'true'
        method: umap
        metric: euclidean
        n_neighbors: '15'
        n_neighbors_file:
            __class__: ConnectedValue
        n_pcs: '50'
        random_seed: '0'
        use_rep: X_pca
normalise_data:
    export_mtx: 'true'
    input_format: anndata
    output_format: anndata_h5ad
    settings:
        __current_case__: 1
        default: 'false'
        exclude:
            __current_case__: 1
            exclude_highly_expressed: 'false'
        key_added: ''
        layer_norm: ''
        layers: ''
        log_transform: 'false'
        save_raw: 'true'
        scale_factor: '1000000.0'
normalise_data_internal:
    export_mtx: 'false'
    input_format: anndata
    output_format: anndata_h5ad
    settings:
        __current_case__: 1
        default: 'false'
        exclude:
            __current_case__: 1
            exclude_highly_expressed: 'false'
        key_added: ''
        layer_norm: ''
        layers: ''
        log_transform: 'true'
        save_raw: 'true'
        scale_factor: '10000.0'
perplexity:
    __job_resource:
        __current_case__: 0
        __job_resource__select: 'no'
    input_type:
        __current_case__: 0
        input_values: 1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50
        parameter_values: list_comma_separated_values
    parameter_name: perplexity
plot_pca:
    basis: pca
    color_by: n_genes
    components: ''
    edges: 'false'
    edges_color: ''
    edges_width: '0.1'
    fig_dpi: '80'
    fig_fontsize: '10'
    fig_frame: 'false'
    fig_size: 7,7
    fig_title: PCA
    gene_symbols_field: ''
    groups: ''
    input_format: anndata
    layer: ''
    legend_fontsize: '10'
    legend_loc: right margin
    neighbors_key: ''
    point_size: ''
    projection: 2d
    sort_order: 'false'
    use_raw: 'true'
resolution:
    __job_resource:
        __current_case__: 0
        __job_resource__select: 'no'
    input_type:
        __current_case__: 0
        input_values: 0.1, 0.3, 0.5, 0.7, 1.0, 2.0, 3.0, 4.0, 5.0
        parameter_values: list_comma_separated_values
    parameter_name: resolution
run_pca:
    extra_outputs: null
    input_format: anndata
    n_pcs: '50'
    output_format: anndata_h5ad
    run_mode:
        __current_case__: 1
        chunked: 'false'
        random_seed: '1234'
        svd_solver: arpack
        zero_center: 'false'
run_tsne:
    embeddings: 'true'
    input_format: anndata
    output_format: anndata_h5ad
    settings:
        __current_case__: 1
        default: 'false'
        early_exaggeration: '12.0'
        fast_tsne: 'false'
        key_added: perplexity_PERPLEXITY
        learning_rate: '400.0'
        n_job: ''
        n_pc: ''
        perplexity: '30.0'
        perplexity_file:
            __class__: ConnectedValue
        random_seed: '1234'
    use_rep: auto
run_umap:
    embeddings: 'true'
    input_format: anndata
    key_added: NEIGHBORS_KEY
    output_format: anndata
    settings:
        __current_case__: 1
        alpha: '1.0'
        default: 'false'
        gamma: '1.0'
        init_pos: spectral
        maxiter: ''
        min_dist: '0.5'
        n_components: '2'
        negative_sample_rate: '5'
        random_seed: '0'
        spread: '1.0'
    use_graph: neighbors_INPUT_OBJ
split_metadata_vars:
    split_parms:
        __current_case__: 6
        input:
            __class__: RuntimeValue
        newfilenames: split_file
        select_allocate:
            __current_case__: 2
            allocate: byrow
        select_ftype: generic
        select_mode:
            __current_case__: 0
            chunksize: '1'
            mode: chunk
        split_method:
            __current_case__: 1
            record_length: '1'
            select_split_method: number
